version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel
    mem_limit: 212m

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - laravel
    mem_limit: 212m

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    mem_limit: 212m
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - db

  queue:
    image: especializati/laravel9-app
    restart: unless-stopped
    mem_limit: 212m
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - app
    networks:
      - laravel

  redis:
    image: redis:latest
    mem_limit: 212m
    networks:
      - laravel

  node-red:
    image: nodered/node-red
    mem_limit: 212m
    ports:
      - "1880:1880"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
